### ISSUE TITLE
5.11 breaks CPAN::Reporter

### ISSUE THREAD

**Issue by twogee** [libwww-perl/URI#101] opened 2022-07-06 02:30 UTC
`Bareword "URI::HAS_RESERVED_SQUARE_BRACKETS" not allowed while "strict subs" in use at URI/_generic.pm line 13.`

**Comment by oalders** [comment] 2022-07-06 02:47
Ping @Perlbotics

**Comment by haarg** [comment] 2022-07-06 06:57
When is this error appearing?

**Comment by Perlbotics** [comment] 2022-07-06 07:06
Hi, I could reproduce this error in a mixed environment where the system perl interferes with this module during testing.
I.e. `prove` fails while `prove -I lib` does not.
Same problem as with `uri-test` script.

**Comment by haarg** [comment] 2022-07-06 09:40
`prove -l` is the correct command to use to test the against the version in `lib`. This was no different before `.` was removed from `@INC`. Having `.` in `@INC` would not help find the modules in `lib`.

The reported issue seems to be regarding an actual installed version of the module. The error would seem to indicate that the install was incomplete or broken in some way. It's worth checking the `$VERSION` in the installed `URI.pm` and `URI/_generic.pm` files.

**Comment by Perlbotics** [comment] 2022-07-06 19:32
Graham (@haarg) , you are absolutely right. First, I've got onto the wrong track, then I gave full throttle m(

Seems, that @twogee's setup loaded another version of `URI.pm` first since the current version would have defined the constant.
@twogee  should deliver more context to decide if this one is really a bug that needs to be fixed.

What do you think of a test/assertion ( in `.t/00.assert.t`) that bails out if it detects that the tests are not going to be run 
against the new `URI.pm` module that is going to be installed (`$URI::VERSION`- or inode-comparison)?

`is( $URI::VERSION, "5.11")`
`   or BAIL_OUT("Test is run against the wrong URI.pm ($INC{'URI.pm'})! Please check your environment.");`

**Comment by oalders** [comment] 2022-07-08 20:46
Closing as this does not appear to be a bug. @twogee if you can demonstrate otherwise, please add to this ticket.

**Closed by oalders** 2022-07-08 20:46 UTC
