### ISSUE TITLE
Bareword "URI::HAS_RESERVED_SQUARE_BRACKETS" not allowed while "strict subs" in use

### ISSUE THREAD

**Issue by mirokado** [libwww-perl/URI#105] opened 2022-07-09 21:12 UTC
URI fails to load, noticed while CPAN invokes CPAN::Reporter

I think there is a dollar sign missing before the identifier at perl/5.26.1/URI/_generic.pm line 13.

Perl version 5.26.1
URI is up to date (5.11).

CPAN::Reporter: Test result is 'pass', All tests successful.
CPAN::Reporter: preparing a CPAN Testers report for WWW-Mechanize-2.10
CPAN::Reporter: sending test report with 'pass' via Metabase
CPAN::Reporter: Test::Reporter: error from 'Test::Reporter::Transport::Metabase:'
Bareword "URI::HAS_RESERVED_SQUARE_BRACKETS" not allowed while "strict subs" in use at /usr/lib/perl5/site_perl/5.26.1/URI/_generic.pm line 13.
Compilation failed in require at /usr/lib/perl5/site_perl/5.26.1/parent.pm line 16.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.26.1/URI/_server.pm line 6.
Compilation failed in require at /usr/lib/perl5/site_perl/5.26.1/parent.pm line 16.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.26.1/URI/http.pm line 8.
Compilation failed in require at /usr/lib/perl5/site_perl/5.26.1/parent.pm line 16.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.26.1/URI/https.pm line 8.
Compilation failed in require at (eval 525) line 1.

**Comment by skaji** [comment] 2022-07-09 22:19
It seems that

* (1) Initially, CPAN or CPAN::Reporter loads outdated URI
* (2) CPAN or CPAN::Reporter upgrades URI to 5.11
* (3) When CPAN or CPAN::Reporter tries to access https url with LWP, it loads URI::https.

A minimal example is:

```perl
#!/usr/bin/env perl
use strict;
use warnings;
use lib "local/lib/perl5";

sub run { warn "--> @_\n"; !system @_ or die }

run 'rm -rf local';
run "curl -fsSL https://cpanmin.us | $^X - -Llocal -nq URI\@5.10";
require URI;
run "curl -fsSL https://cpanmin.us | $^X - -Llocal -nq URI\@5.11";
require URI::https; # load by LWP with https url
```
```
❯ perl test.pl
--> rm -rf local
--> curl -fsSL https://cpanmin.us | /Users/skaji/env/plenv/versions/5.36.0/bin/perl - -Llocal -nq URI@5.10
Successfully installed URI-5.10
1 distribution installed
--> curl -fsSL https://cpanmin.us | /Users/skaji/env/plenv/versions/5.36.0/bin/perl - -Llocal -nq URI@5.11
Successfully installed URI-5.11 (upgraded from 5.10)
1 distribution installed
Bareword "URI::HAS_RESERVED_SQUARE_BRACKETS" not allowed while "strict subs" in use at local/lib/perl5/URI/_generic.pm line 13.
Compilation failed in require at /Users/skaji/env/plenv/versions/5.36.0/lib/perl5/5.36.0/parent.pm line 16.
BEGIN failed--compilation aborted at local/lib/perl5/URI/_server.pm line 6.
Compilation failed in require at /Users/skaji/env/plenv/versions/5.36.0/lib/perl5/5.36.0/parent.pm line 16.
BEGIN failed--compilation aborted at local/lib/perl5/URI/http.pm line 8.
Compilation failed in require at /Users/skaji/env/plenv/versions/5.36.0/lib/perl5/5.36.0/parent.pm line 16.
BEGIN failed--compilation aborted at local/lib/perl5/URI/https.pm line 8.
Compilation failed in require at test.pl line 12.
```

**Comment by skaji** [comment] 2022-07-09 22:25
This kind of issue only happens in CPAN clients,
and should be addressed in CPAN clients side, I think.

**Comment by skaji** [comment] 2022-07-09 22:36
And this is duplicate of #101

**Comment by mirokado** [comment] 2022-07-09 23:39
Thanks for the quick replies. This is clearly more subtle than I had realised! HAS_RESERVED_SQUARE_BRACKETS is a constant defined in URI.pm, _generic.pm has URI as a parent, both URI.pm and _generic.pm compile correctly on my system when I just run perl -c on them.

I have executed fforce install URI in cpan, which should ensure that URI is "upgraded successfully": I will post again after the next cpan update.

**Comment by Perlbotics** [comment] 2022-07-10 14:22
Hi @mirokado, now, you have have a clean installation, alas a buggy one (5.11).
Consider to manually patch `URI.pm` around line 120/130 from
   ` my $orig          = $2;`
to
   ` my $orig          = $2 || return;`
until a patched version is available.

Alternatively, restore 5.10 or see 5.11 section `ENVIRONMENT VARIABLES` for other measures
to restore the previous behavior if your software relies on `scheme:///...`  or `scheme://#...` or `scheme://?...`,
especially `file:///...` or `mailto:...`.
Sorry for the inconvenience.

**Comment by mirokado** [comment] 2022-07-11 00:44
Thank you @Perlbotics, I patched as you suggest (at line 105 here) and tried to install something new (Math::Matrix). This worked fine.
My other machine has just found URI v5.12, and that also installed without problems, so I installed Math::Matrix there too, successfully.
I think you could close this now.

**Comment by oalders** [comment] 2022-07-11 02:17
Thanks @mirokado for opening this issue and thanks @skaji and @Perlbotics for the debugging!

**Closed by oalders** 2022-07-11 02:17 UTC
